baseurl = "https://steemit.netlify.com"
languageCode = "en-us"
title = "STEEM@dapeng"
theme = "hugo-xmin"
googleAnalytics = ""
disqusShortname = "pzhao"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
preserveTaxonomyNames = true
footnotereturnlinkcontents = "↩"

[permalinks]
    post = "/post/:slug/"
    note = "/note/:year/:month/:day/:slug/"

[[menu.main]]
    name = "Home|首页"
    url = "/"
    weight = 1
[[menu.main]]
    name = "About|关于"
    url = "/about/"
    weight = 2
[[menu.main]]
    name = "Categories|类目"
    url = "/categories/"
    weight = 3
[[menu.main]]
    name = "Tags|标签"
    url = "/tags/"
    weight = 4
[[menu.main]]
    name = "Subscribe|订阅"
    url = "/index.xml"

[params]
    description = "A website built through Hugo and blogdown."
    footer = "All rights reserved  &copy; [dapeng](https://steemit.com/@dapeng) 2017 \n\n Powered by [R blogdown](https://bookdown.org/yihui/blogdown/), [Hugo](https://gohugo.io/), and [Xmin](https://github.com/yihui/hugo-xmin)"
