<!DOCTYPE html>
<html lang="en-us">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Steem Watch 大鹏观察（A1） @justyy | STEEM@dapeng</title>
    <link rel="stylesheet" href="/css/style.css" />
    <link rel="stylesheet" href="/css/fonts.css" />
    
  </head>

  <body>
    <nav>
    <ul class="menu">
      
      <li><a href="/">Home|首页</a></li>
      
      <li><a href="/about/">About|关于</a></li>
      
      <li><a href="/categories/">Categories|类目</a></li>
      
      <li><a href="/tags/">Tags|标签</a></li>
      
      <li><a href="/index.xml">Subscribe|订阅</a></li>
      
    </ul>
    <hr/>
    </nav>

<div class="article-meta">
<h1><span class="title">Steem Watch 大鹏观察（A1） @justyy</span></h1>
<h2 class="author">dapeng</h2>
<h2 class="date">2017-08-15 16:27 GMT</h2>
</div>

<main>
<p>原文链接: <a href="https://steemit.com/cn/@dapeng/steem-id-report-1-justyy-1">steemit</a>, <a href="https://cnsteem.com/cn/@dapeng/steem-id-report-1-justyy-1">cnsteem</a>, <a href="https://chainbb.com/cn/@dapeng/steem-id-report-1-justyy-1">chainbb</a>, <a href="https://busy.org/cn/@dapeng/steem-id-report-1-justyy-1">busy</a>, <a href="https://raw.githubusercontent.com/pzhaonet/steem_mirror/master/content/post/steem-id-report-1-justyy-1.md">markdown</a></p>

<p>为了活跃 CN 区的气氛，同时也提醒大家注意个人数据的安全，我试着发起个活动，名叫“大鹏观察”。活动的方式很简单：你报名，我干活儿。</p>

<p>在前不久，我对 @tumutanzi  公开的用户数据进行了粗略的分析。刚一挖，@tumutanzi 就<a href="https://steemit.com/cn/@dapeng/no-1s-of-his-steem-posts-steem#@tumutanzi/re-dapeng-no-1s-of-his-steem-posts-steem-20170802t081240570z">觉得他要红了</a>，果然他就红了，<a href="https://steemit.com/cn/@tumutanzi/why-does-ned-delegate-so-much-steem-power-to-tumutanzi-and-thanks-steemit-ned-tumutanzi-400-steem-power">得了 50 万 SP</a>，而大家对数据的反响还不错。“大鹏观察”将用类似的方法，对其他的 Steem 用户数据进行同样分析。选取哪些用户呢？这就需要你的参与了。</p>

<p><strong>参加方式有两种：</strong></p>

<ol>
<li><p><strong>点名</strong>。@A 可以点名来挖 @B 的用户数据，只需 @A 和 @B 两人在最新一期留言，两人均同意即可。点不点赞请随意。</p></li>

<li><p><strong>自荐</strong>。自己点自己的名字。只需在最新一期留言即可。点不点赞请随意。</p></li>
</ol>

<p>本活动计划每周举办一期，每期挖一个 ID 的最近 100 篇帖子。周二前报名，周三发布。点名优先于自荐（为了活跃社区气氛），被点过名的具有优先点名权（希望弄成一个接龙）。重复一遍，优先顺序是：</p>

<p><strong>接龙 &gt; 点名 &gt; 自荐</strong></p>

<p>如果报名人数多的话，置顶者优先（容易找）; 如果没人参与的话，就暂停或终止。游戏规则如果以后有调整的话，以最新一期公布的规则为准，并且最终解释权归 @dapeng。</p>

<p>虽然这些数据全部是公开的，每个人都可以轻易得到，但是我们仍然尊重当事人的意见，需经同意才开挖。大家对活动有什么建议，也??迎提出来，毕竟现在的数据分析还很粗浅，将来可供拓展的方向很多。</p>

<p>“大鹏观察”第一期的志愿者是 @justyy，他是<a href="https://steemit.com/cn/@dapeng/no-1s-of-his-steem-posts-steem#@justyy/re-dapeng-no-1s-of-his-steem-posts-steem-20170802t091703102z">自荐报的名</a> 。希望 @justyy 跟 @tumutanzi 一样，一挖他就红，一红就赞我。</p>

<p>In my previous posts, I roughly analyzed a steem user&rsquo;s data and got some interesting results. From this post, I will analyze more users&rsquo; data weekly. If you are volunteered, please upvote this post and leave a message. One ID per week. First come, first serve. Our first volunteer is @justyy.</p>

<hr />

<p>前情回顾：</p>

<p>Previously on <em>Steem ID Report</em>:</p>

<ul>
<li><p><a href="https://steemit.com/cn/@dapeng/steemit">Steemit 的新手们，你们考虑过数据隐私的问题吗</a></p></li>

<li><p><a href="https://steemit.com/steemit/@dapeng/new-steemians-have-you-have-thought-about-your-data-privacy">New Steemians, have you ever thought about your data privacy?</a></p></li>

<li><p><a href="https://steemit.com/cn/@dapeng/steem-a-preliminary-analysis-of-a-steem-id-s-data">看到他暴露的 Steem 用户数据后我震惊了 a preliminary analysis of a steem ID&rsquo;s data</a></p></li>

<li><p><a href="https://steemit.com/cn/@dapeng/no-1s-of-his-steem-posts-steem">NO.1s of his steem posts 坛中酒醉： steem 的帖子到底应该怎么写 </a></p></li>
</ul>

<p><img src="https://steemitimages.com/DQmNX1zxNPpZEB9uqEbJ4hnNTKB3yEbw8gDnaAwTnrsZfVt/justyy.png" alt="justyy.png" /></p>

<p>This is a report of the Steemit ID @justyy. The data were sampled from <a href="https://steemdb.com/">https://steemdb.com/</a> at 2017-08-15 09:35:33 UTC.</p>

<p>本文是 Steemit ID @justyy 的用户数据报道。数据来自 <a href="https://steemdb.com/">https://steemdb.com/</a>, 采集时间是 2017-08-15 09:35:33 UTC。</p>

<p>Basic information 基本信息</p>

<hr />

<table>
<thead>
<tr>
<th align="left">_id</th>
<th align="left">created</th>
<th align="left">post_count</th>
<th align="left">followers_count</th>
<th align="left">following_count</th>
</tr>
</thead>

<tbody>
<tr>
<td align="left">justyy</td>
<td align="left">2016-08-20 18:36</td>
<td align="left">1552</td>
<td align="left">506</td>
<td align="left">288</td>
</tr>
</tbody>
</table>

<p>Top posts 帖子之最</p>

<hr />

<p>In this section we listed some of @justyy&rsquo;s top posts.</p>

<p>我们来看看 @justyy 发布的帖子里的几个第一名，研究一下究竟是什么样的帖子最受欢迎。</p>

<p><strong>Top post with the most characters. 字符最多的帖子</strong></p>

<ul>
<li><a href="https://steemit.com/@'r%20id'/software-engineer-interview-question-how-many-ways-from-a-to-c-via-b-a-b-c">Software Engineer Interview Question - How Many Ways from A to C via B? 软件工程师面试技巧之 从A到B再到C有多少种方法?</a>，含 9664 个字符。</li>
</ul>

<p><strong>Top post with the most figures. 插图最多的帖子</strong></p>

<ul>
<li><a href="https://steemit.com/@justyy/taking-kids-to-old-macdonald-farm-photography-and-a-16-sbd-give-away-old-macdonald-16-sbd">Taking Kids to Old MacDonald Farm (Photography and a 16 SBD give-away) 带孩子去 Old MacDonald 农场 (弟弟为什么哭呢? 第一个答对奖励 16 SBD)</a>，含 34 张图片。</li>
</ul>

<p><strong>Top post with the most edits. 修改次数最多的帖子</strong></p>

<ul>
<li><a href="https://steemit.com/@justyy/sql-software-engineer-interview-question-the-second-highest">软件工程师数据库面试技巧之 SQL中的第二名记录 Software Engineer Interview Question - The Second Highest</a>，发布后被作者修改了 7 次。</li>
</ul>

<p><strong>Top post with the longest time between the publication and the final edit. 修改间隔最长的帖子</strong></p>

<ul>
<li><a href="https://steemit.com/@justyy/software-engineer-interview-question-how-to-improve-dynamic-programming-space-complexity">Software Engineer Interview Question – How to Improve Dynamic Programming Space Complexity? 进一步改进动态规化的空间复杂度</a>，发布 165.2 小时即 6.9 天之后，作者做了最后一次修改。</li>
</ul>

<p><strong>Top post with the longest life time. 生命力最顽强的帖子</strong></p>

<ul>
<li><a href="https://steemit.com/@justyy/30">Technology-driven or Business-model-driven? 技术优先还是商业模式优先 – 献给在30多岁还在写代码的朋友们</a>，发布 238 小时即 9.9 天后仍然有人留言。</li>
</ul>

<p><strong>Top post with the most upvotes. 得票数最多的帖子</strong></p>

<ul>
<li><a href="https://steemit.com/@justyy/technically-images-can-be-stored-on-blockchain-steemit">Technically Images can be Stored on BlockChain 差一点 SteemIt 就可以把图片也存在区块链上了</a>，得到 151 个赞。</li>
</ul>

<p><strong>Top post with the most payout value. 赚钱最多的帖子</strong></p>

<ul>
<li><a href="https://steemit.com/@justyy/50mm-f1-8">Picnic Photography using Canon 50mm F1.8 入手 加能50mm定焦镜头 F1.8</a>，收入为 288 美元。</li>
</ul>

<p>Followers and following 粉丝情况</p>

<hr />

<p>@justyy has 506 followers. @justyy followed 288 ID in total, in which 123 IDs interacted with @justyy bidirectionally, while 165 IDs did not follow him, including:</p>

<p>@justyy 的粉丝有 506 个 ID，@justyy 关注的 ID 总数是 288。其中，有 123 个 ID 跟 @justyy 是双向关注的，而 165 个ID 虽然被 @justyy 关注，但却没有关注 @justyy，他们是：</p>

<p>@ability, @acrich, @act, @adsactly, @akareem, @alexkoshy, @allasyummyfood, @alphacore, @amedeo, @analisa, @andrewlyte, @apsu, @arbitrarykitten, @askaran, @berksaustins, @blackbunny, @boomshikha, @booster, @borganic, @bryantandk, @btsabc, @bue, @cheetah, @chelsea20, @coinkingz, @colmanlamkh, @completelyanon, @creadordelfuturo, @crimea, @crystalpacheco30, @dalao, @dan, @daut44, @davidding, @deearchi, @deepwaterscrypto, @dollface, @donkeypong, @duda, @duplet, @elfkitchen, @exan, @fancy-shmancy, @feelapi, @forexbrokr, @freedomnation, @frostfan, @fshnkey, @fundurian, @furion, @glitterfart, @good-karma, @hanshotfirst, @head10, @heimindanger, @hendrikdegrote, @holays, @homeartpictures, @hr1, @ifty40, @incrediblesnow, @iphonetraveler, @ipkiss, @jademont, @jakkk, @january1992, @jinbo, @joshsigurdson, @just-me, @justtryme90, @kamaroopi, @karenmckersie, @kawaiiiiiiii030, @kaykobad-reza, @kevinwong, @khunpoom, @king-crypto, @kingjan, @kishore1988, @kitcat, @kyleb15, @laodr, @lemooljiang, @lenatramper, @leobliss, @lilywang, @lingfei, @linuslee0216, @lisadang, @livingfree, @livinguktaiwan, @luis10salas, @marius19, @markangeltrueman, @marzuky, @minnowbooster, @minnowsupport, @mostafa.amin, @mrwanderlust, @mygoblin, @ned, @nextgen622, @nextgencrypto, @nicolemoker, @nigulax, @nter, @null, @oksanasemenova, @pakyeechan, @palashsaha, @penguinpablo, @pinaynomad, @pizzachain, @poloniex, @promoted, @qcb, @rakiblove, @randowhale, @randowhalebonus, @randowhalefund, @raziell, @rea, @reggaemuffin, @renzhichu, @robrigo, @roelandp, @rok-sivante, @sean1980, @slowwalker, @somebody, @someone, @sophiachan, @steemit-health, @steemiteducation, @steepshot, @stephenkendal, @super-man, @sv67216721, @sweetsssj, @sylejmanbajgora, @sylvia1997, @terinadx, @the.masses, @thecryptofiend, @thedonfreeman, @theking, @themarkymark, @timool, @timsaid, @titusfrost, @trafalgar, @tsinrong, @twinkledrop, @tylerdourden, @ulion, @upboat, @vitap, @wang, @xaero1, @xiaohui, @xiaoxijie, @yey, @yukimaru, @yyyy, @zealsun</p>

<p>On the other hand, those who followed @justyy but @justyy did not follow (yet) were:</p>

<p>反过来，关注了 @justyy 却未被 @justyy 关注的有：</p>

<p>@a-condor, @a-jeffrey, @a3ar, @aafeng, @aaronhouu, @abdo.sharaby, @abraham01, @abupasi.alachy, @acge, @adam486, @adeel99, @adforce83, @ahmedezzat, @aijeong, @alanhohoho, @alecsadler, @alexzhan, @alhasan, @alienposts, @ammadkhalid, @andre-verbrick, @angelamei, @anja-caballero, @aqeelmalik, @arielthemermaid, @arkoko, @arnoldwish, @artintelicoinves, @azazqwe, @azirgraff, @babasikandar, @bago, @bernardchapin, @bertimusx, @biddle, @bilalhaider, @binodsinghdhami, @blueheaven, @bobiecayao, @bocaiwen, @born2win, @boyhaqi, @brianchen, @bring, @britt.the.ish, @brnofre, @calinconst, @carlobelgado, @carlosd14, @carobetc, @celestialme, @cenai07, @chance777, @changkun, @chelseanews, @chencool, @cherrypick, @cjstewart1984, @coinbitgold, @coinsine, @cophey, @crypt0news, @crypto.don, @cryptochamo, @cryptokiing, @cryptomonitor, @cryptonnn, @cryptopie, @crystone, @dafahd, @dan-wilson, @daniel007, @daniellimcm, @darmaputra92, @davinger, @detol, @dickoverdale, @dimidrolshina, @dinocreative, @dixydator, @dolov, @dr-stafford, @dragos0897, @dreamcatchers, @dreamstream, @drewzshots, @drrq, @duckmast3r, @dukekjams, @duytruongnguyen, @dwightjaden, @edith1990, @elements, @ellocosaurus, @eltooni, @emonandels, @emsweet, @enazwahsdarb, @epeakinfo, @ernestine, @eslamelnagar, @evgsk, @evhannugrahaaa, @excessivetravel, @exploretraveler, @fatma, @faustino, @fazulujjan, @fire-fly, @firepower, @fitexercise, @fitinfun, @fkofficials, @followseveryone, @forthecraic, @fractal, @freeman01, @freethink, @gabrieliusart, @gamemusic, @gatmi, @geneeverett, @georgetan93, @gergi6a, @ghasemkiani, @globaldoodlegems, @gnimeets, @go4it, @gowldie, @grildrig, @hafeezurrehman, @hag228, @haishen, @hamzaoui, @harmonyhomestead, @hawk1987, @healthycell, @healthytips, @helene, @hendra.hrv, @hengist-horsa, @hereforawhile, @hiroyamagishi, @hoof, @hopsken, @hqfzone, @iamnotageek, @idealkollari, @idx, @imagediet, @imako, @imash, @imranroza, @infinitysci, @instructor2121, @investlimestone, @iqbalbireuen, @irphotography, @irrs, @isacoin, @ishaq, @ismaour, @itissimple, @izbing, @jack8831, @jacker, @jaikumar, @jarendesta, @jejangkit, @jetmirm, @jezhead, @jhenyen-17, @jiangchen, @jigs3716, @joanaltres, @jocool, @johnlue, @johnnyray, @jones420, @joseburgos, @joydip8116, @jukas, @julee, @junyi, @kam.ila, @kanhaiyalal1, @karliks, @kartikk, @kassimbass, @katy-adelson, @katythompson, @kdogdiggles13, @khalilalfamahera, @kimamaxgreen, @kingscoin, @knowledge-trust, @kona, @kristiana, @laboulangdexav, @ladyrebecca, @landeberg, @lannocc, @lautenglye, @ldn-undiscovered, @ledygaga25, @liangfengyouren, @lifetech101, @linminquan, @logic, @longfield98, @lordgangler, @lordofthemidges, @lunaticenigma, @luocj, @lupo, @lykencrypto, @lynx, @mac-gallery, @madsweeney, @madus, @mady27, @manosteel211, @markd, @maro666, @mastergreen, @maxer27, @maxtill94, @mayun, @mehdikh19, @melowd, @mianfahad, @mikega, @mikeshoman, @minknsa, @minnyfatty, @mohamedrafik, @monalishabiswas, @moneyminer, @morshedranan, @mouradb4, @mrceebo, @mrnastykilla, @mydarlings2, @myson, @mytamilabiz, @nadirnaji, @nandibear, @nandikafuture, @new-game-coin, @nicolebh, @nigelmarkdias, @nikhilguru, @nirmalprajapati, @nocrypto4oldmen, @nollza, @notonlyfood, @notregme, @nunojesus, @orianaarmand, @ouba2, @paansingtomar, @pablito, @pakforex, @phoo, @physicfactor, @phytonian, @pistox, @polyurethane, @pomelo, @pptx, @pqlenator, @prateek547, @prufarchy, @qipashuo, @quintomudigo, @quoteoftheday, @raheelaslam111, @rahulmakhija, @ransty, @raoharoon, @rasool584, @ravivshachar, @rawansaeed, @rdickey, @reachfem24, @redtea, @resteem.bot, @reyes907, @richforever, @rikusalomaki, @rishi556, @rmaxhuni, @rmp, @roba, @robertolopez, @robi8888, @rodneyaspiras, @rojo, @romitroksharan, @ronel, @rundmc, @ryan313, @safwaninisam, @sallykwitt, @sandeepsaini, @sarahsarah, @schlijk, @sebcamtv, @sergey44, @seugerry, @shaheer001, @shahzaib, @sharebaby, @sheikhfarooq, @shengjian, @showoff, @shresthaprince07, @simonpeter35, @simonsayz, @siniceku, @skyefox, @smartcasual, @sofiya, @soheilsadeqi, @soi-green, @sosolala, @sshh, @stackin, @steem.engine, @steemit1234, @steemitph, @steemitprime, @steemlinks, @stuffy, @surrealist, @sweetpanda, @sweety170, @syh7758520, @sylviamiller, @tabishez, @talalofficial, @tanko, @tarakki, @tastetwist, @tayyabanoor, @team101, @tecca, @teddy7, @tensaix2j, @teukuarmia, @the-mountain, @thepsychguide, @thestar, @tigerhite1, @tinoei, @tonyboney, @towardsthesun, @ulfr, @uniiq, @vajola, @vargapauline, @vermillionfox, @vpcc, @vsoutdoorsnaps, @wahyusaputra, @wallsnow, @wayforhappiness, @wereviewit, @whydowork, @wiedy, @wlcpu, @worldwidetravel, @xiobus, @yaserphys, @yash0108, @youngjerv, @zainalabidin, @zauberware, @zero9, @zeroshiki, @zerozero777, @zhuqiankun, @zulfahmi2141</p>

<p>Active time 活跃时间</p>

<hr />

<p>The following figure shows @justyy&rsquo;s active time. The green line indicates @justyy&rsquo;s register time on Steem.</p>

<p>下图是 @justyy 自注册以来的发帖时间图，图里每个点代表一篇帖子，往左水平看对应的是发帖的时刻，往下垂直看是发帖的日期。时区是 UTC，请自行根据自己所在时区修正。</p>

<p><img src="https://steemitimages.com/DQmQHVcfTyeVrEP15Zdmkj6BYMphmCSJPJYMvnY61YNKBLT/unnamed-chunk-10-1.png" alt="unnamed-chunk-10-1.png" /></p>

<p><img src="https://steemitimages.com/DQme19EddNJte9KFPt4CevQPh7AR5zGxWrXmViYqRrboqnK/unnamed-chunk-11-1.png" alt="unnamed-chunk-11-1.png" /></p>

<pre><code>##     para     value

## 1    min  0.100000

## 2     1q 11.700000

## 3 median 17.800000

## 4     3q 21.750000

## 5    max 23.800000

## 6  lower -3.337500

## 7  upper 36.787500

## 8   mean 16.066000

## 9     sd  5.953765
</code></pre>

<p>The figure above shows the frequency of @justyy&rsquo;s posts.</p>

<p>上图显示的是 @justyy 一天24小时里发帖的频次，横坐标是每天的几点钟，阴影面积越大的时段，发帖数就越多。</p>

<p>Attitude to posts 对帖子的态度</p>

<hr />

<p><img src="https://steemitimages.com/DQmRJzsGrrT38PXr8d8aWapHnywFN2brSvMmRhUYzBqZg3Y/unnamed-chunk-12-1.png" alt="unnamed-chunk-12-1.png" /></p>

<p>The figure above shows how many edits for each post. Averagely a post was edited 1.8 time(s). The most edits was 7.</p>

<p>上图是每个帖子的编辑次数，图里每个点代表一篇帖子，往左水平看对应的是该帖被编辑的次数。单篇帖子最多被修改了 7 次，最少是 0 次，平均 1.8 次。</p>

<table>
<thead>
<tr>
<th align="left">category</th>
<th align="right">Freq</th>
</tr>
</thead>

<tbody>
<tr>
<td align="left">bitcoins</td>
<td align="right">1</td>
</tr>

<tr>
<td align="left">cambridge</td>
<td align="right">1</td>
</tr>

<tr>
<td align="left">cn</td>
<td align="right">85</td>
</tr>

<tr>
<td align="left">date</td>
<td align="right">1</td>
</tr>

<tr>
<td align="left">gadget</td>
<td align="right">1</td>
</tr>

<tr>
<td align="left">gardening</td>
<td align="right">1</td>
</tr>

<tr>
<td align="left">linux</td>
<td align="right">1</td>
</tr>

<tr>
<td align="left">photography</td>
<td align="right">5</td>
</tr>

<tr>
<td align="left">programming</td>
<td align="right">1</td>
</tr>

<tr>
<td align="left">steemit</td>
<td align="right">2</td>
</tr>

<tr>
<td align="left">travel</td>
<td align="right">1</td>
</tr>
</tbody>
</table>

<p>The table above shows the categories (the first tags) of @justyy&rsquo;s posts. @justyy posted most posts in &lsquo;cn&rsquo;.</p>

<p>上面的数据表格是 @justyy 发帖的首选分区的次数。@justyy 发帖最多的首选分区是 &lsquo;cn&rsquo;.</p>

<p>Quality and money 帖子的质量和收入</p>

<hr />

<p><img src="https://steemitimages.com/DQmeAqkTKwvDzKPaJ44VcmAkCBw4twXJ3fXPncyEX1KERu6/unnamed-chunk-14-1.png" alt="unnamed-chunk-14-1.png" /></p>

<pre><code>##     para     value

## 1    min   0.00000

## 2     1q   6.98400

## 3 median  32.99850

## 4     3q  51.23500

## 5    max 287.92800

## 6  lower -58.00200

## 7  upper 116.22100

## 8   mean  40.27136

## 9     sd  45.49615
</code></pre>

<p>Now let&rsquo;s talk about money. The figure above shows the dollars @justyy got from each post. Averagely @justyy earned 40.27 dollars per post, with the maximum of 287.93 dollars from one post.</p>

<p>现在我们来谈谈钱。上图显示的是单篇帖子收入的分布。横坐标是美元，阴影面积越大，对应美元的帖子数量越多。 @justyy 单帖收入最高为287.93美元，平均每帖收入为40.27 美元。</p>

<p><img src="https://steemitimages.com/DQmNN7wwag2RSGgYAS6VC8YfbTWTd1jHrQhc8gtRXaGF6Ka/unnamed-chunk-15-1.png" alt="unnamed-chunk-15-1.png" /></p>

<pre><code>##     para     value

## 1    min   0.20000

## 2     1q  14.66667

## 3 median  31.91667

## 4     3q  68.54167

## 5    max 238.13333

## 6  lower -65.13958

## 7  upper 148.34792

## 8   mean  49.28714

## 9     sd  50.75661



## [1] &quot;2017-08-11 17:16:00 UTC&quot;



## [1] &quot;shenchensucc&quot;



## [1] &quot;2017-08-01 19:08:00 UTC&quot;
</code></pre>

<p><img src="https://steemitimages.com/DQmbyJ8S6zisNkCNPPKB5Jk7wKPvZi4tiyqXgH1JAbGhkRc/unnamed-chunk-16-1.png" alt="unnamed-chunk-16-1.png" /></p>

<p>The figure above shows the trend of @justyy&rsquo;s money per post.</p>

<p>上图显示的是每帖收入的时间趋势。</p>

<p><img src="https://steemitimages.com/DQmTWCYJKAhh2P44N6x4YYD4Vg5MnxbNLw5mY3Wv9BEUYVh/unnamed-chunk-17-1.png" alt="unnamed-chunk-17-1.png" /></p>

<p>The figure above shows the upvote number of each post. Averagely @justyy earned 40 upvotes per post, with the maximum of 151 upvotes.</p>

<p>上图是 @justyy 帖子获得的投票数。 @justyy 单帖得到的点赞数最高为 151 个，平均每帖得赞 40 个。</p>

<p>怪了， @justyy 的单帖获赞越来越多，单帖收入却越来越少，这是在走亲民路线？</p>

<hr />

<p>以上是对 Steem 账号 @justyy 的初??分析。感谢关注“大鹏观察”。欢迎参加下一期的活动，也欢迎提出宝贵意见。谢谢。</p>

</main>

  <footer>
  <div id="disqus_thread"></div>
<script type="text/javascript">
    var disqus_shortname = 'pzhao';
    var disqus_identifier = 'https:\/\/steemit.netlify.com\/post\/steem-id-report-1-justyy-1\/';
    var disqus_title = 'Steem Watch 大鹏观察（A1） @justyy';
    var disqus_url = 'https:\/\/steemit.netlify.com\/post\/steem-id-report-1-justyy-1\/';

    (function() {
        var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
        dsq.src = '//' + disqus_shortname + '.disqus.com/embed.js';
        (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
    })();
</script>
<noscript>Please enable JavaScript to view the <a href="http://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>
<a href="http://disqus.com" class="dsq-brlink">comments powered by <span class="logo-disqus">Disqus</span></a>

<script src="//yihui.name/js/math-code.js"></script>
<script async src="//cdn.bootcss.com/mathjax/2.7.1/MathJax.js?config=TeX-MML-AM_CHTML"></script>

<script async src="//yihui.name/js/center-img.js"></script>

  
  <hr/>
  All rights reserved  &copy; <a href="https://steemit.com/@dapeng">dapeng</a> 2017</p>

<p>Powered by <a href="https://bookdown.org/yihui/blogdown/">R blogdown</a>, <a href="https://gohugo.io/">Hugo</a>, and <a href="https://github.com/yihui/hugo-xmin">Xmin</a>
  
  </footer>
  </body>
</html>

